In [3]:
import pandas as pd

In [176]:
def fibonacci_number(n):
    assert 0 <= n <= 65
    if n <= 1:
        return n
    f_list = list(range(0, n+1))
    f_list[0] = 0
    f_list[1] = 1
    for i in range(2, n+1):
        f_list[i] = f_list[i-1] + f_list[i-2]
    return f_list[n]

In [2]:
def last_digit_of_fibonacci_number(n):
    assert 0 <= n <= 10 ** 7
    if n <= 1:
        return n
    f_list = list(range(0, n+1))
    f_list[0] = 0
    f_list[1] = 1

    for i in range(2, n+1):
        f_list[i] = f_list[i-1] % 10 + f_list[i-2] % 10
    return f_list[n] % 10

In [53]:
def last_digit_of_the_sum_of_fibonacci_numbers_naive(n):
    assert 0 <= n <= 10 ** 18

    if n <= 1:
        return n

    fibonacci_numbers = [0] * (n + 1)
    fibonacci_numbers[0] = 0
    fibonacci_numbers[1] = 1
    for i in range(2, n + 1):
        fibonacci_numbers[i] = fibonacci_numbers[i - 2] + fibonacci_numbers[i - 1]

    return sum(fibonacci_numbers) % 10

In [ ]:
def last_digit_of_the_sum_of_fibonacci_numbers_naive(n):
    assert 0 <= n <= 10 ** 18

    if n <= 1:
        return n

    fibonacci_numbers = [0] * (n + 1)
    fibonacci_numbers[0] = 0
    fibonacci_numbers[1] = 1
    for i in range(2, n + 1):
        fibonacci_numbers[i] = fibonacci_numbers[i - 2] + fibonacci_numbers[i - 1]

    return sum(fibonacci_numbers) % 10

def last_digit_of_the_sum_of_fibonacci_numbers(n):
    assert 0 <= n <= 10 ** 18

    if n <= 1:
        return n
    f_list = list(range(0, n+1))
    f_list[0] = 0
    f_list[1] = 1

    for i in range(2, n+1):
        
    return sum(f_list) % 10

In [218]:
def last_digit_of_the_sum_of_fibonacci_numbers_new(n,m):
    p_period = p_period_length(m)
    n = n % p_period
    if n <= 1:
        return n
    f_list = list(range(0, n+1))
    f_list[0] = 0
    f_list[1] = 1
    for i in range(2, n + 1):
        f_list[i] = last_digit_of_fibonacci_number(i-1) + last_digit_of_fibonacci_number(i-2) 
    return sum(f_list) % m

In [85]:
def sum_of_fibonacci_numbers_naive(n):
    if n <= 1:
        return n

    fibonacci_numbers = [0] * (n + 1)
    fibonacci_numbers[0] = 0
    fibonacci_numbers[1] = 1
    for i in range(2, n + 1):
        fibonacci_numbers[i] = fibonacci_numbers[i - 2] + fibonacci_numbers[i - 1]  
    return sum(fibonacci_numbers)

In [149]:
def p_period_length(m):
    previous, current = 0, 1
    for i in range(0, m**2):
    for i in range(0, m**2):
        previous, current = current, (previous + current) % m
        if previous == 0 and current == 1:
            return i + 1

In [148]:
def fibonacci_number_again(n, m):
    assert 0 <= n <= 10 ** 18 and 2 <= m <= 10 ** 3
    p_period = p_period_length(m)
    n = n % p_period
    if n <= 1:
        return n
    previous, current = 0, 1
    for _ in range(n - 1):
        previous, current = current, (previous + current)
    return current % m

In [219]:
def generate_fibonacci(n):
    fn = []
    lasts = []
    last_sums = []
    sums = []
    last_sums_opt = []
    last_sums_new = []
    mods = []
    for i in range (0,n+1):
        fn.append(fibonacci_number(i))
        lasts.append(last_digit_of_fibonacci_number(i))
        last_sums.append(last_digit_of_the_sum_of_fibonacci_numbers_naive(i))
        sums.append(sum_of_fibonacci_numbers_naive(i))
        last_sums_opt.append(last_digit_of_the_sum_of_fibonacci_numbers(i))
        last_sums_new.append(last_digit_of_the_sum_of_fibonacci_numbers_new(i,10) )
        mods.append(fibonacci_number_again(i,60))
    return fn, lasts, last_sums, sums, last_sums_opt, last_sums_new, mods

In [220]:
numbers, lasts, last_sums, sums, last_sums_opt, last_sums_new, mods = generate_fibonacci(65)

In [221]:
df = pd.DataFrame()
df['Fib'] = numbers
df['last digit of fib'] = lasts
df['last digit of sum of fib - naive'] = last_sums
df['last digit of sum of fib'] = last_sums_opt
df['sum of fib'] = sums
df['last digit of sum of fib - new'] = last_sums_new
df['sum of mods'] = mods
df

,Fib,last digit of fib,last digit of sum of fib - naive,last digit of sum of fib,sum of fib,last digit of sum of fib - new,sum of mods
0,0,0,0,0,0,0,0
1,1,1,1,1,1,1,1
2,1,1,2,2,2,2,1
3,2,2,4,4,4,4,2
4,3,3,7,7,7,7,3
...,...,...,...,...,...,...,...
61,2504730781961,1,1,1,6557470319841,1,41
62,4052739537881,1,2,2,10610209857722,2,41
63,6557470319842,2,4,4,17167680177564,4,22
64,10610209857723,3,7,7,27777890035287,7,3
65,17167680177565,5,2,2,44945570212852,2,25

In [222]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df)

,Fib,last digit of fib,last digit of sum of fib - naive,last digit of sum of fib,sum of fib,last digit of sum of fib - new,sum of mods
0,0,0,0,0,0,0,0
1,1,1,1,1,1,1,1
2,1,1,2,2,2,2,1
3,2,2,4,4,4,4,2
4,3,3,7,7,7,7,3
5,5,5,2,2,12,2,5
6,8,8,0,0,20,0,8
7,13,3,3,3,33,3,13
8,21,1,4,4,54,4,21
9,34,4,8,8,88,8,34
10,55,5,3,3,143,3,55
11,89,9,2,2,232,2,29
12,144,4,6,6,376,6,24
13,233,3,9,9,609,9,53
14,377,7,6,6,986,6,17
15,610,0,6,6,1596,6,10
16,987,7,3,3,2583,3,27
17,1597,7,0,0,4180,0,37
18,2584,4,4,4,6764,4,4
19,4181,1,5,5,10945,5,41
20,6765,5,0,0,17710,0,45
21,10946,6,6,6,28656,6,26
22,17711,1,7,7,46367,7,11
23,28657,7,4,4,75024,4,37
24,46368,8,2,2,121392,2,48
25,75025,5,7,7,196417,7,25
26,121393,3,0,0,317810,0,13
27,196418,8,8,8,514228,8,38
28,317811,1,9,9,832039,9,51
29,514229,9,8,8,1346268,8,29
30,832040,0,8,8,2178308,8,20
31,1346269,9,7,7,3524577,7,49
32,2178309,9,6,6,5702886,6,9
33,3524578,8,4,4,9227464,4,58
34,5702887,7,1,1,14930351,1,7
35,9227465,5,6,6,24157816,6,5
36,14930352,2,8,8,39088168,8,12
37,24157817,7,5,5,63245985,5,17
38,39088169,9,4,4,102334154,4,29
39,63245986,6,0,0,165580140,0,46
40,102334155,5,5,5,267914295,5,15
41,165580141,1,6,6,433494436,6,1
42,267914296,6,2,2,701408732,2,16
43,433494437,7,9,9,1134903169,9,17
44,701408733,3,2,2,1836311902,2,33
45,1134903170,0,2,2,2971215072,2,50
46,1836311903,3,5,5,4807526975,5,23
47,2971215073,3,8,8,7778742048,8,13
48,4807526976,6,4,4,12586269024,4,36
49,7778742049,9,3,3,20365011073,3,49
50,12586269025,5,8,8,32951280098,8,25
51,20365011074,4,2,2,53316291172,2,14
52,32951280099,9,1,1,86267571271,1,39
53,53316291173,3,4,4,139583862444,4,53
54,86267571272,2,6,6,225851433716,6,32
55,139583862445,5,1,1,365435296161,1,25
56,225851433717,7,8,8,591286729878,8,57
57,365435296162,2,0,0,956722026040,0,22
58,591286729879,9,9,9,1548008755919,9,19
59,956722026041,1,0,0,2504730781960,0,41
60,1548008755920,0,0,0,4052739537880,0,0
61,2504730781961,1,1,1,6557470319841,1,41
62,4052739537881,1,2,2,10610209857722,2,41
63,6557470319842,2,4,4,17167680177564,4,22
64,10610209857723,3,7,7,27777890035287,7,3
65,17167680177565,5,2,2,44945570212852,2,25